@token = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njg5NDg2MTZ9.A4NVA0TKtSulzgVLPZX71I2NhXLJZ0MTF5iz-7MGqeE"


### Login with user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin@psdentistry.com",
    "password": "password"
}

### Create a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "flip",
    "username": "flip",
    "email": "flip@test.com",
    "password": "password",
    "password_confirmation": "password"
}

### Get all users without token
GET http://localhost:3000/api/users


### Get a user
GET http://localhost:3000/api/users/Janet
Authorization: "{{token}}"

### Get all users
GET http://localhost:3000/api/users
Authorization: "{{token}}"


# ### Successfully delete a booking
# DELETE http://localhost:3000/api/bookings/2
# Authorization: "{{token}}"


# ### Not found - delete a booking that does not exist
# DELETE http://localhost:3000/api/bookings/999
# Authorization: "{{token}}"

# ### Successfully create a booking
# POST http://localhost:3000/api/bookings
# Authorization: "{{token}}"
# Content-Type: application/json

# {
#     "user_id": 4,
#     "atend_id":  4,
#     "doctor_id": 2, 
#     "label": "11:30am",   
#     "hour": 11,
#     "minutes": 30,
#     "booked" : false
# }

### Get a user from ID
GET http://localhost:3000/api/users/7
Authorization: "{{token}}"

### Get bookings belonging to logged in user
GET http://localhost:3000/api/bookings
Authorization: "{{token}}"

### Get doctors
GET http://localhost:3000/api/doctors
Authorization: "{{token}}"

### Get specific doctor
GET http://localhost:3000/api/doctors/1
Authorization: "{{token}}"

### Get bookings 6 (only shows you your bookings)
GET http://localhost:3000/api/bookings/5
Authorization: "{{token}}"

### Get all current logged ins bookings
GET http://localhost:3000/api/bookings
Authorization: "{{token}}"

### Successfully update a booking
PUT http://localhost:3000/api/bookings/3
Content-Type: application/json
Authorization: "{{token}}"

{
    "label": "07:30am",
    "hour": 7,
    "minutes": 30

}

### Get search booking for doctor 2
GET http://localhost:3000/api/doctors/1/bookings
Authorization: "{{token}}"

### Successfully UPDATE a booking with doctor and atend in url
PUT http://localhost:3000/api/doctors/1/bookings
Authorization: "{{token}}"
Content-Type: application/json

{
    "atend_id":  6,
    "label": "09:30am",   
    "hour": 9,
    "minutes": 30
}

### get all atends in table
GET http://localhost:3000/api/atend
Authorization: "{{token}}"